name: IClaim
version: '${project.version}'
main: de.chiakuma.iclaim.Plugin_IClaim
api-version: 1.19
authors: [ ChiAkuma ]
description: Allows players to claim and manage chunks of land on the server
website: plugins.chiakuma.de
commands:
  iclaim:
    usage: /iclaim
    description: jaa ne is klar
    aliases:
      - icm
